FROM node:18-alpine

WORKDIR /app

COPY package.json .

RUN yarn

COPY . .

ARG VITE_API_URL
ENV VITE_API_URL $VITE_API_URL

# Print environment variable
RUN echo "Print VITE_API_URL $VITE_API_URL"

RUN yarn build

EXPOSE 8080

CMD [ "yarn", "run", "dev" ]