# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/var/www/html
#     networks:
#       - laravel-network
#     depends_on:
#       - mysql
#     environment:
#       DB_HOST: mysql
#       DB_PORT: 3306
#       DB_DATABASE: ${DB_DATABASE}
#       DB_USERNAME: ${DB_USERNAME}
#       DB_PASSWORD: ${DB_PASSWORD}

#   mysql:
#     image: mysql:latest
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_USER: ${DB_USERNAME}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - laravel-network

# networks:
#   laravel-network:
#     driver: bridge

# volumes:
#   mysql_data:


version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    container_name: gd
    volumes:
      - ../:/var/www/html/
      - ./conf/apache:/etc/apache2/sites-enabled/
      - ./conf/php:/etc/php/5.5/
      - ./shared:/shared

  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/
      - ./shared:/shared
    environment:
      MYSQL_DATABASE: upd8
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

